Repository Free-Onboarding-team4/admin-product-regist, pull requests merged in 2022-01, with the labels that each got.

#3 상품 정보 고시 UI 및 기능 구현
  src/components/Layouts/SectionBlock.jsx
  src/components/ProductInformation/AddItem.jsx
  src/components/ProductInformation/Information.jsx
  src/components/ProductInformation/ProductInformation.jsx
  src/components/ProductInformation/index.js
  src/pages/ProductRegist.jsx
  src/pages/hh.jsx
Labels: ✨ Feature, 🎨 Style

#8 ✨정보고시 추가 제거 기능 구현 및 utils에 onAddDel 추가
  package-lock.json
  src/components/ProductInformation/AddItem.jsx
  src/components/ProductInformation/Information.jsx
  src/components/ProductInformation/ProductInformation.jsx
  src/utils/onAddDel.js
Labels: ✨ Feature, ♻️ Refactor

#10 💄y 스크롤 생성
  src/components/ProductInformation/ProductInformation.jsx
  src/utils/onAddDel.js
Labels: ♻️ Refactor, 🎨 Style

#11 💄 상품 소개 이미지 & 구매자 추천 이미지 섹션 추가
  src/components/BasicInformation/BasicInformation.jsx
  src/components/BasicInformation/index.js
  src/components/ImageSection/ImageList.jsx
  src/components/ImageSection/ImageUpload.jsx
  src/components/ImageSection/IntroductionImage.jsx
  src/components/ImageSection/RecommendImage.jsx
  src/components/ImageSection/UploadContainer.jsx
  src/components/ImageSection/index.js
  src/pages/jy.jsx
Labels: ✨ Feature, 🎨 Style

#13 ✨자동완성 기능 구현
  src/components/AutoComplete.js
  src/pages/hh.jsx
Labels: ✨ Feature, 🎨 Style

#16 ✨ 상품 기본 정보 - 상품명 입력 시 상품코드, 재고 노출
  src/components/BasicInformation/BasicInformation.jsx
  src/components/BasicInformation/Inputs.jsx
  src/components/BasicInformation/index.js
Labels: ✨ Feature, 🎨 Style

#17 ✨ 세트옵션, 내부옵션, 세부옵션 Delete기능 구현 완료
  src/components/ProductOption/AdditionalOption.jsx
  src/components/ProductOption/DeleteButton.jsx
  src/components/ProductOption/InnerOption.jsx
  src/components/ProductOption/Input.jsx
  src/components/ProductOption/OptionImage.jsx
  src/components/ProductOption/OptionMain.jsx
  src/components/ProductOption/OptionSet.jsx
  src/components/index.js
Labels: ✨ Feature, enhancement

#19 ✨ 할인율 계산 기능 구현 완료
  src/components/ProductOption/AdditionalOption.jsx
  src/components/ProductOption/InnerOption.jsx
  src/components/ProductOption/InputNumber.jsx
  src/components/ProductOption/OptionImage.jsx
  src/components/ProductOption/OptionMain.jsx
Labels: ✨ Feature, enhancement

#21 ✨ 상품 카테고리 레이아웃 및 로직 구현 완료
  package-lock.json
  package.json
  src/components/Category/ProductCategory.jsx
  src/components/Period/ProductExposure.jsx
  src/components/Period/ProductSale.jsx
  src/data/category.json
  src/pages/ch.jsx
Labels: ✨ Feature, 🎨 Style

#23 Project/refactor
  package-lock.json
  src/components/BasicInformation/AutoComplete.jsx
  src/components/BasicInformation/BasicInformation.jsx
  src/components/BasicInformation/ProductCategory.jsx
  src/components/BasicInformation/index.js
  src/components/ImageSection/IntroductionImage.jsx
  src/components/ImageSection/RecommendImage.jsx
  src/components/Layouts/PageBlock.jsx
  src/components/Layouts/SideNav.jsx
  src/components/Layouts/SideNavList.jsx
  src/components/Layouts/index.js
  src/components/Library/BasicSwitches.jsx
  src/components/Library/DatePickerBox.jsx
  src/components/Library/DateTimeCalender.jsx
  src/components/Library/index.js
  src/components/Period/ProductExposure.jsx
  src/components/Period/ProductPeriod.jsx
  src/components/Period/ProductSale.jsx
  src/components/Period/index.js
  src/components/ProductInformation/AddItem.jsx
  src/components/ProductInformation/Information.jsx
  src/components/ProductInformation/ProductInformation.jsx
  src/components/ProductInformation/index.js
  src/components/ProductOption/AdditionalOption.jsx
  src/components/ProductOption/DeleteButton.jsx
  src/components/ProductOption/InnerOption.jsx
  src/components/ProductOption/InputNumber.jsx
  src/components/ProductOption/OptionImage.jsx
  src/components/ProductOption/OptionMain.jsx
  src/components/ProductOption/OptionSet.jsx
  src/components/ProductOption/index.js
  src/components/Setting/DeliverySetting.jsx
  src/components/Setting/EctSetting.jsx
  src/components/Setting/ProductAgree.jsx
  src/components/Setting/ProductDelivery.jsx
  src/components/Setting/ProductSetting.jsx
  src/components/Setting/index.js
  src/constants/index.js
  src/pages/ProductRegist.jsx
  src/pages/ch.jsx
  src/pages/hh.jsx
  src/pages/hj.jsx
  src/pages/jy.jsx
Labels: ♻️ Refactor

#25 ✨ 상품 배송 설정 토글 로직 기능 구현
  src/components/BasicInformation/ProductCategory.jsx
  src/components/Library/BasicSwitches.jsx
  src/components/Library/index.js
  src/components/Setting/EctSetting.jsx
  src/components/Setting/ProductAgree.jsx
  src/components/Setting/ProductDelivery.jsx
Labels: ✨ Feature
